name: Bug Report
description: "Report something that's broken."
body:
  - type: markdown
    attributes:
      value: "Please read [our full contribution guide](https://laraxgram.github.io/contributions.html#bug-reports) before submitting bug reports. If you notice improper DocBlock, or IDE warnings while using Simula, do not create a GitHub issue. Instead, please submit a pull request to fix the problem."
  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the issue you are facing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Provide detailed steps to reproduce your issue.
    validations:
      required: true
